### ISSUE TITLE
Docker is always "restarting" as status

### ISSUE THREAD

**Issue by xbelanch** [JonnyPtn/zomboi#38]
Is there any way to fix this? 

`d68d7855a731   zomboi-zomboi                                       "python zomboi.py"       17 minutes ago   Restarting (1) 54 seconds ago                                                                                                                                                  zomboi-zomboi-1`

Trying to access to container I received this:

```
$ docker-compose exec zomboi /bin/bash
Error response from daemon: Container d68d7855a731995a8dce2d3d5c804ebf68dc6d91eb845645de70c8dcd2129552 is restarting, wait until the container is running
```

**Comment by JonnyPtn** [comment]
Hard to really say what's going wrong here, I would guess something is causing the server to fail to start which means the container just keeps retrying. We'll need some logs or some more info to tell what's going wrong

If you run the container in interactive mode or maybe try something with the `docker logs` command that may provide some information

**Comment by xbelanch** [comment]
seems it was a mistake of mine?

```
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Traceback (most recent call last):
  File "/home/zomboi/zomboi.py", line 81, in <module>
    zomboi.run(os.getenv("DISCORD_TOKEN"))
  File "/home/zomboi/.local/lib/python3.10/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/home/zomboi/.local/lib/python3.10/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/home/zomboi/.local/lib/python3.10/site-packages/discord/client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "/home/zomboi/.local/lib/python3.10/site-packages/discord/client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```

**Comment by petegilb** [comment]
It's telling you how to fix it in the error: enable `SERVER MEMBER INTENT` in your application/bot section
