### ISSUE TITLE
My bot stopped working

### ISSUE THREAD

**Issue by Bazimek** [JonnyPtn/zomboi#59]
No chat to Discord, no join/disconnect messages. Nothing. Commands like !users are working, bu no output from server to Discord channel.

**Comment by Bazimek** [comment]
Trying some different settings but I am at this error:

ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "zomboi.py", line 70, in on_ready
    zomboi.add_cog(PerkHandler(zomboi, logPath))
  File "/home/spravce/boti/pzold2/perks.py", line 16, in __init__
    self.loadHistory()
  File "/home/spravce/boti/pzold2/perks.py", line 57, in loadHistory
    self.handleLog(*self.splitLine(line))
  File "/home/spravce/boti/pzold2/perks.py", line 68, in handleLog
    user = self.bot.get_cog("UserHandler").getUser(name)
AttributeError: 'NoneType' object has no attribute 'getUser'

**Comment by Bazimek** [comment]
2022-10-29 07:06:31,494:INFO:zomboi: We have logged in as servertest#3221
2022-10-29 07:06:31,494:INFO:zomboi: channel connected
2022-10-29 07:06:31,494:INFO:zomboi: Loading user history...
2022-10-29 07:06:31,495:INFO:zomboi: User history loaded
2022-10-29 07:06:31,495:INFO:zomboi: Loading Perk history...
2022-10-29 07:06:31,495:INFO:zomboi: Perk history loaded
2022-10-29 07:06:31,496:INFO:zomboi: Maps path: /var/lib/pterodactyl/volumes/cc05b822-dc08-492f-8065-3acef196a344/media/maps
2022-10-29 07:06:31,498:INFO:zomboi: Checking rcon to see if the player counter is correct
2022-10-29 07:06:31,604:INFO:zomboi: Synced players successfully!

But nothing in Discord channel

**Comment by Bazimek** [comment]
And the player list is not updating. It updates only with rcon every 5 minutes. I really do not know what is wrong.

**Comment by Bazimek** [comment]
Seems like only the Rcon part of the bot is working, because it is fixing the player, but still not correct player online and no output from bot to Discord.
![image](https://user-images.githubusercontent.com/17622398/198826572-f03a97da-3b1f-4bd3-82e0-0bef737afa78.png)

**Comment by Bazimek** [comment]
Another info. This is in the log. Is it ok?

INFO     discord.client logging in using static token
2022-10-29 12:32:33 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: a2ed897e9e9a047213210bf814e7b15f).

**Comment by JonnyPtn** [comment]
Which version of the game are you on? I have a feeling they changed some of the logging in the latest update which may have broken everything
