### ISSUE TITLE
discord.client: Ignoring exception in on_ready

### ISSUE THREAD

**Issue by UrbanSide** [JonnyPtn/zomboi#62]
```

2022-11-22 02:00:22,402:INFO:zomboi: We have logged in as servertest#4172
2022-11-22 02:00:22,403:INFO:zomboi: channel connected
2022-11-22 02:00:22,405:INFO:zomboi: Loading user history...
2022-11-22 02:00:22,802:INFO:zomboi: User history loaded
2022-11-22 02:00:22,803:INFO:zomboi: Loading Perk history...
[2022-11-22 02:00:22] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\SMOLL.NET\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "D:\ZomboidMods\zomboi-master\zomboi-master\zomboi.py", line 71, in on_ready
    await zomboi.add_cog(PerkHandler(zomboi, logPath))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ZomboidMods\zomboi-master\zomboi-master\perks.py", line 16, in __init__
    self.loadHistory()
  File "D:\ZomboidMods\zomboi-master\zomboi-master\perks.py", line 57, in loadHistory
    self.handleLog(*self.splitLine(line))
  File "D:\ZomboidMods\zomboi-master\zomboi-master\perks.py", line 86, in handleLog
    hours = re.search(r"Hours Survived: (\d+)", message).group(1)
```

**Comment by UrbanSide** [comment]
**Fix found here https://github.com/JonnyPtn/zomboi/issues/29**
