### ISSUE TITLE
Hello! Having some troubles with the bot

### ISSUE THREAD

**Issue by cookedneko** [JonnyPtn/zomboi#75]
Currently set everything up properly and it's still having a hard time accessing files in maps folder it says that maps folder is e

``
2023-06-17 06:12:56,672:INFO:zomboi: Perk history loaded
2023-06-17 06:12:56,673:ERROR:zomboi: Map path /Maps not found and/or no suitable default
2023-06-17 06:12:56,674:INFO:zomboi: Checking rcon to see if the player counter is correct
2023-06-17 06:15:06,578:ERROR:zomboi: [Errno 110] Connect call failed ('redacted', redacted)
2023-06-17 06:15:06,578:ERROR:zomboi: Unable to run players command on rcon -- check rcon options
rcon options
2023-06-17 06:31:46 ERROR    discord.ext.commands.bot Ignoring exception in command option
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/rcon_adapter.py", line 30, in option
    with Client(self.rconHost, self.rconPort, passwd=self.rconPassword, timeout=5.0) as client:
  File "/home/container/.local/lib/python3.11/site-packages/rcon/client.py", line 31, in __enter__
    self.connect(login=True)
  File "/home/container/.local/lib/python3.11/site-packages/rcon/client.py", line 52, in connect
    self._socket.connect((self.host, self.port))
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TimeoutError: timed out
``

**Comment by cookedneko** [comment]
I fixed the map issue by modifying the code, problem now is that it can't seem to access the rcon to the server

**Comment by cookedneko** [comment]
Ok the only problem I have now is with rcon not working, it's failing to connect to the server for some reason

**Comment by JonnyPtn** [comment]
Possibly an issue with the rcon settings on the server - hard to say without more info

The python version of this bot is deprecated now anyway, so will close this for now
