### ISSUE TITLE
Bot stop working

### ISSUE THREAD

**Issue by GameAreaCZ** [JonnyPtn/zomboi#79]
can be deleted

**Comment by GameAreaCZ** [comment]
@glowacki-dev can you help with that please?

**Comment by hernandocav** [comment]
same issue here

**Comment by Grim-reap3r** [comment]
2023-09-02 18:53:23 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
2023-09-02 18:53:23 INFO     discord.client logging in using static token
2023-09-02 18:53:24 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: beac657b8a381b9a8f74c5ee492d0911).
2023-09-02 18:53:26,720:INFO:zomboi: We have logged in as ServerRaport#3859
2023-09-02 18:53:26,721:INFO:zomboi: channel connected
2023-09-02 18:53:26,722:INFO:zomboi: Loading user history...
2023-09-02 18:53:26,726:INFO:zomboi: User history loaded
/home/raport/zomboi.py:71: RuntimeWarning: coroutine 'BotBase.add_cog' was never awaited
  zomboi.add_cog(user_handler)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/raport/zomboi.py:72: RuntimeWarning: coroutine 'BotBase.add_cog' was never awaited
  zomboi.add_cog(ChatHandler(zomboi, logPath))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-09-02 18:53:26,727:INFO:zomboi: Loading Perk history...
2023-09-02 18:53:26 ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/raport/zomboi.py", line 73, in on_ready
    zomboi.add_cog(PerkHandler(zomboi, logPath))
  File "/home/raport/perks.py", line 16, in __init__
    self.loadHistory()
  File "/home/raport/perks.py", line 57, in loadHistory
    self.handleLog(*self.splitLine(line))
  File "/home/raport/perks.py", line 69, in handleLog
    user = userHandler.getUser(name)
AttributeError: 'NoneType' object has no attribute 'getUser'

**Comment by Grim-reap3r** [comment]
Hello...
