### ISSUE TITLE
I'm Getting a disallowed intent error

### ISSUE THREAD

**Issue by chibiakurei** [JonnyPtn/zomboi#87]
I know basically nothing about any of this. but when I do everything you've said and then use dotnet run I get this error>

System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4014: "Disallowed intent(s)."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
   
   I've looked it up and its about its intents within the developer portal but i can't seem to figure out what I need to change to get it to work.

**Comment by pcmunro** [comment]
You need to go into the Discord development platform and select the bot you made and enable all intents.
